version: 2
references:
  container_config: &container_config
    working_directory: ~/app
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:9.11.2-jessie-browsers
      - image: mongo:3.4.16-jessie
  restore_app_cache: &restore_app_cache
    restore_cache:
      key: v1-dependencies-{{ checksum "package-lock.json" }}

  restore_frontend_cache: &restore_frontend_cache
    restore_cache:
      key: v1-api-dependencies-{{ checksum "apps/frontend/package-lock.json" }}

  bootstrap: &bootstrap
    run:
      name: Install npm
      command:  |
        npm install
        $(npm bin)/lerna bootstrap --stream

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - *restore_app_cache
      - *restore_frontend_cache

      - *bootstrap

      - run:
          name: Test
          command: npm test

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-api-dependencies-{{ checksum "apps/frontend/package-lock.json" }}
          paths:
            - apps/frontend/node_modules

  deploy_staging:
    <<: *container_config
    steps:
      - checkout
      - *restore_app_cache
      - *restore_frontend_cache
      - run: pm2 deploy staging

  deploy_production:
    <<: *container_config
    steps:
      - checkout
      - *restore_app_cache
      - *restore_frontend_cache
      - run: pm2 deploy production


workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
